test_closest (__main__.TestExercice) ... FAIL
test_coordinates (__main__.TestExercice) ... FAIL
test_linear_values (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_linear_values (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_linear_values
    self.assertListEqual(
  File "/usr/lib/python3.8/unittest/case.py", line 1118, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib/python3.8/unittest/case.py", line 1065, in assertSequenceEqual
    if item1 != item2:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
FAIL: test_closest (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 42, in test_closest
    self.assertEqual(
AssertionError: 0 != 3 : Erreur dans le remplacement de caractère

======================================================================
FAIL: test_coordinates (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 29, in test_coordinates
    np.testing.assert_array_equal(
  File "/home/runner/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/runner/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 768, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
  File "/home/runner/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 745, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
Mauvaise réponse
x and y nan location mismatch:
 x: array([[ 0.      ,       nan],
       [14.142136,  0.785398],
       [ 2.236068, -0.463648]])
 y: array([[ 0.      ,  0.      ],
       [14.142136,  0.785398],
       [ 2.236068, -0.463648]])

----------------------------------------------------------------------
Ran 3 tests in 0.018s

FAILED (failures=2, errors=1)
